baseurl: https://wttlora.netlify.app/
relativeURLs: true
languageCode: en-us
title: WTT LoRaWAN
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:  
  - \.Rmd$  
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Commands
      url: https://srv-lab-t-430.zhaw.ch/wildtiertracking/index.html
    - name: Data
      url: https://srv-lab-t-430.zhaw.ch/wildtiertracking/api/parsed-data/json
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
fig_width: 6 
fig_height: 4 