---
title: 'F04 '
author: Stoller Sandro
date: '2021-02-16'
slug: F04
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Server connection
```{r serverconetion, , message=FALSE, warning=FALSE, include=FALSE}
  library(jsonlite)
  library(tidyverse)
  library(sf) 
  library(tmap)
  library(scales) 
  library(kableExtra)
   # make json, then make list
  mydata <- fromJSON("https://srv-lab-t-430.zhaw.ch/wildtiertracking/api/parsed-data/json", flatten = TRUE)
  
  mydata$Time <- as.POSIXct(strptime(mydata$Time, format = '%Y-%m-%dT%H:%M:%S'), format = '%Y-%m-%dT%H:%M:%S')
  mydata$Payload.Content.Time <- as.POSIXct(strptime(mydata$Payload.Content.Time , format = '%Y-%m-%dT%H:%M:%S'), format = '%Y-%m-%dT%H:%M:%S')
  # summarize the counts of satallites
  mydata  <- mydata %>%
  mutate(sumSat = rowSums(select(., contains("Payload.Content.GpsCount"  )))) 
### round.POSIXt(Sys.time(), "h") ###
```


# Shows Payload last 3 Days
```{r payload, echo=FALSE, warning=FALSE , message=FALSE}

 mydata %>%    dplyr::filter(DeviceEUI == "3633333053397F04") %>% 
                dplyr::filter(Time >= Sys.Date()-3)%>%
  ggplot(aes(Time, Payload.Type) )+
  geom_point()+
  theme_bw()+
scale_x_datetime(breaks = date_breaks("1 day"),
  minor_breaks = date_breaks("3 hour"))+
   labs(caption = paste("Last compiled on", "2021-03-08 16:00:00"   ))


```
 

```{r from Text, echo=FALSE, message=FALSE, warning=FALSE}

F04 <- mydata  %>%
  dplyr::filter(DeviceEUI == "3633333053397F04")%>% 
                dplyr::filter(Time >= Sys.Date()-7)



# Batterielevel F04 
F04Status <- F04 %>% 
  dplyr::filter(Payload.Type== "Status")  

ggplot(F04Status, aes(x = as.Date(Time), y = Payload.Content.BatteryVoltage, colour = DeviceEUI)) +
  geom_point() +
    geom_line()+
  facet_wrap( ~ DeviceEUI)+
    theme(legend.position = "none",panel.background = element_blank(),
            panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "gray"))+
    labs(title="Plot der Batteriespannung",
        x ="Datum", y = "Batteriespannung",
        caption = paste("Last compiled on", "2021-03-08 16:00:00"    ))
```
   
  # Show Status Table from the last 7 Days

```{r Status as Table, echo=FALSE}

F04Status  %>% filter(Time >= Sys.Date()-7)%>%
select(c("Time","Rssi","Payload.Content.Temperature","Payload.Content.BatteryVoltage","sumSat"))%>%
        rename(Temperatur = Payload.Content.Temperature , 
               BatteryVoltage = Payload.Content.BatteryVoltage)%>%
  kbl(caption = "Statusmassages from F04") %>%
  kable_classic(full_width = F, html_font = "Cambria", position = "left")%>%
    footnote(general = print(paste("Last compiled on", "2021-03-08 16:00:00"   )))
```
    
    
    

# Show Gateways der letzen 2 Tage
```{r echo=FALSE, message=FALSE, warning=FALSE}
print(paste("Last compiled on", "2021-03-08 16:00:00"))
F04heute <- F04 %>% dplyr::filter(Time >= Sys.Date()-2) %>%
                      dplyr::filter(GatewayLon <= 10.6677 )%>%
                      dplyr::filter(GatewayLon >= 5.7349 )%>%
                      dplyr::filter(GatewayLat <= 47.9163 )%>%
                      dplyr::filter(GatewayLat >= 45.6755 )

F04gw_heute <- st_as_sf(x = F04heute ,                          
           coords = c("GatewayLon", "GatewayLat"),
           crs = 4326) %>% 
            st_transform( 2056)

tmap_mode("view")
tm_basemap(server = "OpenStreetMap")+
tm_shape(F04gw_heute) +
tm_dots("DeviceEUI",alpha = 1, size = 0.3 )
```
    

# Localisationen seit "2021-02-03" 
```{r echo=FALSE, message=FALSE, warning=FALSE}
print(paste("Last compiled on", "2021-03-08 16:00:00"))
F04LocData <- mydata  %>%
  dplyr::filter(DeviceEUI == "3633333053397F04")%>% 
          dplyr::filter(Payload.Type== "Location")%>%
          dplyr::filter("Payload.Content.Alt" != 0.0)%>%
          dplyr::filter(Payload.Content.Time > "2021-02-12 00:00:02")


df_F04 <- st_as_sf(x = F04LocData ,                         
           coords = c("Payload.Content.Lon", "Payload.Content.Lat"),
           crs = 4326)
df_F04 <- st_transform(df_F04, 2056)

df_F04_lines <- df_F04 %>% dplyr::summarise(do_union = FALSE) %>% st_cast("LINESTRING")

tmap_mode("view")
tm_basemap(server = "OpenStreetMap")+
tm_shape(df_F04) +
tm_dots("DeviceEUI",alpha = 0.5, size=0.1,col="orange"  ) +
tm_shape(df_F04_lines) +
tm_lines( alpha = 0.4)     
  
```

# Location as table

```{r loctable F04, echo=FALSE, fig.height=6, fig.width=6}

mydata  %>%
    dplyr::filter(DeviceEUI == "3633333053397F04")%>% 
          dplyr::filter(Payload.Type== "Location")%>%
        filter(Time >= Sys.Date()-7)%>%
        rename(Latitude =Payload.Content.Lat , 
               Longitude = Payload.Content.Lon ,
               Altitude = Payload.Content.Alt )%>%
        select(c("Time","Rssi","Latitude","Longitude","Altitude"))%>%
        kbl(caption = "Locationmassage from F04") %>%
        kable_classic(full_width = F, html_font = "Cambria", position = "left") %>%
    footnote(general = print(paste("Last compiled on", "2021-03-08 16:00:00" )))
```

