---
title: "Lokalisationen-Visualisierungen"
author: "Stll"
date: '2021-01-24T21:48:51-07:00'
output: pdf_document
tags:
- R Markdown
- plot
- regression
categories: R
---

# Einleitung     
Datendownload und verarbeitung von LoRaWAN Downlinks

# Server connection
```{r serverconetion, message=FALSE, warning=FALSE, include=FALSE}
  library(jsonlite)
  library(tidyverse)
  library(sf)
  library(tmap)
  library(scales) 
library(kableExtra)
   # make json, then make list
  mydata <- fromJSON("https://srv-lab-t-430.zhaw.ch/wildtiertracking/api/parsed-data/json", flatten = TRUE)
  
  mydata$Time <- as.POSIXct(strptime(mydata$Time, format = '%Y-%m-%dT%H:%M:%S'), format = '%Y-%m-%dT%H:%M:%S')
  mydata$Payload.Content.Time <- as.POSIXct(strptime(mydata$Payload.Content.Time , format = '%Y-%m-%dT%H:%M:%S'), format = '%Y-%m-%dT%H:%M:%S')

```

- Last compiled on `r format(Sys.time(), '%d %B, %Y')`

# Shows Payload last Day
```{r echo=FALSE, message=FALSE, warning=FALSE ,results='hide',fig.keep='all'}

 mydata %>%    group_by(DeviceEUI) %>%
                dplyr::filter(Time >= Sys.Date()-1)%>%
  ggplot(aes(Time, Payload.Type))+
  geom_point()+
  theme_bw()+
  scale_x_datetime(breaks = date_breaks("3 hours"),
  labels =  time_format(format = "%H:%M", tz = "UTC"))+
  facet_wrap( ~ DeviceEUI, ncol = 1)

time_format(format = "%H:%M", tz = "UTC")


```
 

```{r from Text, echo=FALSE, message=FALSE, warning=FALSE}
locdata <- mydata %>% 
          dplyr::filter(Payload.Type== "Location")%>%
          dplyr::filter("Payload.Content.Alt" != 0.0)# %>%
         # dplyr::select(-c(9:28))
# The "official" extent for all our country-scale analysis (i.e. Switzerland) is:
  # Latitude: Min 45.6755, Max  47.9163
  # Longitude: Min 5.7349, Max 10.6677
locdata <- locdata %>%  dplyr::filter(Payload.Content.Lon <= 10.6677 )%>%
                      dplyr::filter(Payload.Content.Lon >= 5.7349 )%>%
                      dplyr::filter(Payload.Content.Lat <= 47.9163 )%>%
                      dplyr::filter(Payload.Content.Lat >= 45.6755 )


statdata <- mydata %>% 
          dplyr::filter(Payload.Type== "Status") # %>%
          #dplyr::fselect(- c())
```

  

# Plot der Gateways die Uplinks hatten   
- letze Woche
```{r Gateways, echo=FALSE, message=FALSE, warning=FALSE}
heute <- mydata %>% dplyr::filter(Time >= Sys.Date()-7) 

gw_heute <- st_as_sf(x = heute ,                         
           coords = c("GatewayLon", "GatewayLat"),
           crs = 4326) %>%
            st_transform(2056)

tmap_mode("view")

tm_shape(gw_heute) +
tm_dots("DeviceEUI",alpha = 1, size = 0.3)
```

# All Devives
```{r Namen der Devices, echo=FALSE}
Namen <- tibble(
  DeviceEUI = c(
"0031873B48B65522", "3633333053397F03", "3433333051378219" ,"3633333053397F02",
 "00BC251BBBD699F9", "3633333053397F04", "3633333053397C18", "3433333073378518",
"3433333062378619", "00D359FDBB66FE3E", "343333305C378219"), 
Name = c( "F55",   "F03",   "F56",  "F02",   "Fyy",  "F04",    "Fxx",   "F65",  "F38", "F08", "F01"   ),  
Art = c(  "Primär","Primär","Solar","Primär","Primär","Primär","Primär","Solar","Solar","Primär", "Solar"  ),
Wo = c(   "Kora",  "Stll",  "Stll", "Stll",  "Stll",  "Suts",  "Suts",  "Stll", "Neye", "Kuh"  ,"Stll"))

Namen %>% arrange(Art,Name)%>%
kbl(caption = "Devices und Namen") %>%
        kable_classic(full_width = F, html_font = "Cambria", position = "left") 
```



# All Fixes on a map
```{r plot on a map, echo=FALSE, message=FALSE, warning=FALSE}
F02	<-locdata %>% filter(DeviceEUI =="3633333053397F02") %>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F02 <- st_transform(F02, 2056)

F03	<-locdata %>% filter(DeviceEUI =="3633333053397F03")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F03	 <- st_transform(F03, 2056)

F04	<-locdata %>% filter(DeviceEUI =="3633333053397F04")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F04	 <- st_transform(F04, 2056)

F08	<-locdata %>% filter(DeviceEUI =="00D359FDBB66FE3E")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F08	 <- st_transform(F08, 2056)

F55 <- locdata %>% filter(DeviceEUI =="0031873B48B65522")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F55 <- st_transform(F55, 2056)

Fxx	<-locdata %>% filter(DeviceEUI =="3633333053397C18")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
Fxx	 <- st_transform(Fxx, 2056)

Fyy	<-locdata %>% filter(DeviceEUI =="00BC251BBBD699F9")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
Fyy	 <- st_transform(Fyy, 2056)

F01	<-locdata %>% filter(DeviceEUI =="343333305C378219")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F01	 <- st_transform(F01, 2056)

#F38		<-locdata %>% filter(DeviceEUI =="3433333062378619")%>%
#st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
#F38		 <- st_transform(F38	, 2056)

F56		<-locdata %>% filter(DeviceEUI =="3433333051378219")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F56		 <- st_transform(F56	, 2056)

F65	<-locdata %>% filter(DeviceEUI =="3433333073378518")%>%
st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),crs = 4326)
F65	 <- st_transform(F65, 2056)

# all Devices as df 

tmap_mode("view")

tm_shape(F02) +
  tm_dots("DeviceEUI",alpha = 0.8,col="red", size = 0.1)+
tm_shape(F03) +
  tm_dots("DeviceEUI",alpha = 0.8,col="yellow", size = 0.1)+
tm_shape(F04) +
  tm_dots("DeviceEUI",alpha = 0.8,col="green", size = 0.1)+
tm_shape(F08) +
  tm_dots("DeviceEUI",alpha = 0.8,col="cyan", size = 0.1)+
tm_shape(F55) +
  tm_dots("DeviceEUI",alpha = 0.8,col="blue", size = 0.1)+
tm_shape(Fxx) +
  tm_dots("DeviceEUI",alpha = 0.8,col="black", size = 0.1)+
tm_shape(Fyy) +
  tm_dots("DeviceEUI",alpha = 0.8,col="magenta", size = 0.1)+
tm_shape(F01) +
  tm_dots("DeviceEUI",alpha = 0.8,col="azure", size = 0.1)+
tm_shape(F56) +
  tm_dots("DeviceEUI",alpha = 0.8,col="orange", size = 0.1)+
tm_shape(F65) +
  tm_dots("DeviceEUI",alpha = 0.8,col="violet", size = 0.1)

```

# Ohrmarke 100   
- Trajektorie seit der Besenderung 2021-01-11 20:00
```{r F08, , echo=FALSE, message=FALSE, warning=FALSE}
df2 <- locdata %>% dplyr::filter(DeviceEUI == "00D359FDBB66FE3E") %>%
                  dplyr::filter(Payload.Content.Time >= "2021-01-11 20:00:00")%>%  
    st_as_sf(coords = c("Payload.Content.Lon", "Payload.Content.Lat"),
           crs = 4326)
df2 <- st_transform(df2, 2056)

df2_lines <- df2 %>% dplyr::summarise(do_union = FALSE) %>% st_cast("LINESTRING")

tmap_mode("view")
tm_basemap(server = "OpenStreetMap")+
tm_shape(df2) +
tm_dots("DeviceEUI",alpha = 0.5, size=0.1,col="yellow")+
tm_shape(df2_lines ) +
tm_lines( alpha = 0.4)   

#centum_klm <- df2_lines %>% st_transform(4326) %>% # just because wgs84...
 # select(Description = Time) 

  
#   st_write(centum_klm, "test.kml", driver = "kml", delete_dsn = TRUE)

```


    

```{r create .kml file, eval=FALSE, include=FALSE}

#centum_klm <- df2_lines %>% st_transform(4326) %>% # just because wgs84...
 # select(Description = Time)

  
#   st_write(centum_klm, "test.kml", driver = "kml", delete_dsn = TRUE)

```

